### ISSUE TITLE
How n2n select which physical interface to choose/select ?

### ISSUE THREAD

**Issue by pocha** [meyerd/n2n#10]
I have deployed n2n (edge client) with mwan3 (load balancer cum failover) on an Openwrt router at a remote location. 

There seems to be startup issues sometimes where the edge client starts putting up `sendTo` errors in the log. I am yet to figure out why these issues happen but for time being, I have put a cron script that checks for such issues & restart edge. That seem to _blanket_ fix the problem for time being.

The bigger issue is - after network restart, I experience that the edge client has become inaccessible (I am unable to ssh into the router). This stays for a reasonably long time. I suspect this is because the physical interface n2n tap interface choose to bridge is possibly down. Interestingly, this does not create any sendTo error logs. I have the router logs exported out to a remote server running rsyslogd so I could check on the remote server & ascertain this. 

My assumption is - the code `tuntap_open` while opening the socket, selects a physical interface (or kernel does that . .sorry I am not really a network/kernel guy). If the physical interface goes down, it does not switch to the other working interface. 

To blanket fix this problem, I am going to extend the cron script I have written to check for ping to a remote (always up) edge client & if the ping fails, restart edge client hoping that this time, the kernel is going to choose the right interface. 

I am not sure if this is actually a bug (or issue with kernel). So thought of checking with you about 2 things 
1. Do you think this is a genuine issue ?
2. If yes, can this be fixed in a better way ? I am kind of sick of doing these blanket solutions. As an engineer, I dont like sub-optimal solutions being pushed :(.

**Comment by meyerd** [comment]
Hi, if you look up the kernel documentation on how to open the tun/tap device, the code is doing the correct thing (see, e.g. here https://www.kernel.org/doc/Documentation/networking/tuntap.txt). However, I suspect, that the code does not check, whether the tap device is removed in the mean time. On the other hand, I suspect, the problem could also be on the other end: the edge retains a data structure with socket fds pointing to the sockets, where the other peers can be reached. If those get invalidated, the packets cannot be sent out to those. Unfortunately, I also don't know exactly, how the kernel handles this situation and if the packets simply get dropped if this happens.

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
