### ISSUE TITLE
Feature request: private super node

### ISSUE THREAD

**Issue by fpemud** [meyerd/n2n#11]
Currently, super node can receive registration from any edge node.
I'd like to build a super node to which only my edge nodes are allowed to register.

Implementation suggestion:
Add -k/-K argument to supernode command and add --supernode-key argument to edge command so that the registration process can be encrypted too.

n2n is really great and unique.

**Comment by skyformat99** [comment]
Agree!
It would be nice if you could add a user name and password.

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
