### ISSUE TITLE
Use IPv6 for transport between edges and supernodes

### ISSUE THREAD

**Issue by Akuna-Tarata** [meyerd/n2n#12]
At this time the aren't left many ipv4 connections from the internet provider for private sector.
Many of my friends and I used n2n since many years. But now we can't use it anymore.
Are there any plans to provide ipv6 as transport-protocoll?
Or is there even a possibility to use a mix through the multiple supernode-feature?

Would be nice if we can use n2n again to connect ipv4 (LAN) over ipv6 (internet)

**Comment by meyerd** [comment]
Hi,
unfortunately, I personally cannot devote much time to the n2n project right now. It would definitely be a nice feature, but I expect, that quite a bit of the network and routing table code has to be extended to support ip6 addresses. Feel free to implement an create a pull-request.

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
