### ISSUE TITLE
Android porting

### ISSUE THREAD

**Issue by tianna1121** [meyerd/n2n#15]
Hi, I don't want to use the android version of n2n. So, I tried to use ndk-build to build n2n_v1. I fixed the /dev/tun problem as well as the ifconfig bug. Everything seems OK. However, the Android edge cannot be accessed by other edges.... Any suggestions? Thx

**Comment by meyerd** [comment]
Hi, unfortunately I have no particular knowledge about the network intrinsics on android. I guess that you have to have a rooted phone or use the vpn networking capabilities of android. That in turn would require to rewrite n2n in java as far as I see. I would approach the problem by using a accesspoint where you can debug the network traffic send from and to the android device and disable encryption to see what is going wrong...

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
