### ISSUE TITLE
Edge Error

### ISSUE THREAD

**Issue by littleplus** [meyerd/n2n#22]
I build it in Centos 6/7 x64.
n2n edge starts without any error, but when I try to ping it from another machine, it's down with under errors:

 kernel: edge[9062]: segfault at 100000000 ip 0000000100000000 sp 00007fff083ee798 error 14 in libz.so.1.2.7[7f9f42c05000+15000]

and then:

appex: edge0 is down
appex: edge0 is down
appex: edge0 is del

**Comment by meyerd** [comment]
While I appreciate when such errors get reported, it is incredibly difficult to find out what is going wrong without exact the same setup that you have. I suspect, that there is something wrong with the usage of libz but I cannot in any way guess where this should be coming from without further information or any other means of reproducing the error. Sorry.

**Comment by littleplus** [comment]
Thanks for your reply, I get solved by using the same client and server made by the ntop's source file.
