### ISSUE TITLE
WARNING: Bad supernode parameter (-l <host:port>)

### ISSUE THREAD

**Issue by lucktu** [meyerd/n2n#23]
When I use n2n v1 like this:
edge -d a1 -a 10.0.0.13 -c n2n -k n2n -l a.b.c:10082 -M 1300 -r -b

Get some  messages every minute:
WARNING: Bad supernode parameter (-l <host:port>)

For what?  Thanks a lot!

**Comment by meyerd** [comment]
You really should use the new version 2, a lot of issues are unfixed in v1
