### ISSUE TITLE
N2n compiles errors on windows7 x64

### ISSUE THREAD

**Issue by ellermister** [meyerd/n2n#26]
N2n compiles errors on windows7 x64

![c 2f5w2va 3t9oz ub 2 u](https://user-images.githubusercontent.com/23046078/33932196-3ef1b4ec-e02d-11e7-9626-7802dc0a5fcf.png)

**win7x64, vs2015,openssl-0.9.8k**

how to solve the problem?

**Comment by meyerd** [comment]
Can you try putting

`#define _strncasecmp _strnicmp`

somewhere in the `win32/n2n_win32.h` file and try to recompile?

**Comment by ellermister** [comment]
![aaa](https://user-images.githubusercontent.com/23046078/34284007-e0bfae9a-e709-11e7-847b-dd0e3b22430b.jpg)


I already  to add this code, not solve the problem.

**Comment by meyerd** [comment]
Well, you shouldn't add this define outside the win32 ifdef.
The other undefined references _SCM_start and so on I don't know where this could possibly stem from? Very odd setup you have.

**Comment by ellermister** [comment]
well, the project `https://github.com/ntop/n2n`   is compiles success!
but,you can't exchange data with him on this project.

Thanks,Several of my Linux platforms are using your project.
'suppernode' on windows can compile success,the `edge` but not.

I hope you can help me out. 

I'm trying to install a vs2015 on win10, if success and I'll  reply to you.

**Comment by ellermister** [comment]
I  have solved `_strncasecmp ` define.
function call in `edge.c `, I change the `_strncasecmp` to `_strncasecmp_test`.
and  the `#define strncasecmp_test _strnicmp` putting in file `n2n_win32.h`.
recompile ,there are only 3 errors left.

![i4nz4hlh b2b46 alqbntq2](https://user-images.githubusercontent.com/23046078/34327306-eae94c20-e8fb-11e7-97b5-df8bd486f4cc.png)


![qq 20171224225435](https://user-images.githubusercontent.com/23046078/34327368-6eed9c6e-e8fd-11e7-9a60-5be6415d4320.png)


`SCM_Start，SCM_Install，SCM_Remove`
How to define implement these functions?

**Comment by meyerd** [comment]
Hopefully the last commit fixed the issue. Can you test that please as I have no windows installation. For the SCM* issues, please regenerate the project file from cmake and then try to recompile. The relevant code is in `win32/win-scm.c` in case you want do dig further.

**Comment by ellermister** [comment]
Well,I have solved this problem.
There are two ways.

1. edit the file `win32/DotNet/n2n.vcproj` or `win32/DotNet/n2n.vcxproj`
add item `<ClCompile Include="..\win-scm.c" />` into ItemGroup
eg:
![qq 20171226114105](https://user-images.githubusercontent.com/23046078/34346356-b2ebacaa-ea31-11e7-91ba-21b386865424.jpg)

recompile success!

2. edit the file `n2n_v2/CMakeLists.txt`
add code `add_library(scm win32/win-scm.c)` into WIN32
![qq 20171226114906](https://user-images.githubusercontent.com/23046078/34346479-ccb5baee-ea32-11e7-9cf6-fd9cf2203a23.jpg)

and remove `n2n_test` item
`add_executable(n2n_test n2n_test.c)
target_link_libraries(n2n_test n2n)`

recompile success!

Thanks Meyerd!
