### ISSUE TITLE
Issue on running edge

### ISSUE THREAD

**Issue by isabelle1208** [meyerd/n2n#31]
Hello !
When I enter this order,
`edge -d n2n -a 2.2.2.2 -c mynetwork -k encryptme -u 99 -g 99 -p 50001 -M 1200 -l 121.42.231.10:22222
`
the edge always shows like this.

17/Jan/2018 20:27:25 [     edge.c:1144] Using supernode 121.42.231.10:22222
17/Jan/2018 20:27:25 [tuntap_linux.c:  38] Interface n2n has MAC 4A:65:C4:42:9A:ED
17/Jan/2018 20:27:25 [     edge.c:1342] Interface up. Dropping privileges to uid=99, gid=99
17/Jan/2018 20:27:25 [     edge.c:1351] Binding to local port 50001
17/Jan/2018 20:27:25 [     edge.c: 672] Registering with supernode
17/Jan/2018 20:27:25 [     edge.c:1376] 
17/Jan/2018 20:27:25 [     edge.c:1377] Ready

17/Jan/2018 20:27:25 [     edge.c:1443] STATUS: pending=0, operational=0
17/Jan/2018 20:28:27 [     edge.c: 672] Registering with supernode
17/Jan/2018 20:29:27 [     edge.c: 672] Registering with supernode
17/Jan/2018 20:30:27 [     edge.c: 672] Registering with supernode
17/Jan/2018 20:31:27 [     edge.c: 672] Registering with supernode
17/Jan/2018 20:32:27 [     edge.c: 672] Registering with supernode
17/Jan/2018 20:33:27 [     edge.c: 672] Registering with supernode
17/Jan/2018 20:34:28 [     edge.c: 672] Registering with supernode
17/Jan/2018 20:35:28 [     edge.c: 672] Registering with supernode
17/Jan/2018 20:36:28 [     edge.c: 672] Registering with supernode
17/Jan/2018 20:37:28 [     edge.c: 672] Registering with supernode

Why the edge cannot connect the supernode successufully?
I hope that you can give me answer.

**Comment by meyerd** [comment]
Try if the supernode is actually reachable by UDP on the specified port.
You can increase the verbosity by adding `-v` (more v's increase verbosity)

**Comment by isabelle1208** [comment]
Thanks.
I have already run the edge successfully.
Because I didn't execute the edge on the server.
