### ISSUE TITLE
Compiling the openwrt version of n2n won't work.

### ISSUE THREAD

**Issue by diandengs** [meyerd/n2n#32]
i use the n2n/n2n_v2/openwrt/kamikaze/Makefile make on the debian to openwrtSDK, but wrong is :

snmp@debian:/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64$ make package/n2n/compile V=99
Collecting package info: done
#
# configuration written to .config
#
make[1]: Entering directory '/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64'
make[2]: Entering directory '/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/package/n2n'
. /OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/include/shell.sh; gzip -dc /OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/dl/n2n-gitn2n_v2.tar.gz | tar -C /OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/n2n-gitn2n_v2/.. -xf - 
touch /OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/n2n-gitn2n_v2/.prepared_a75e3c6d07fbe02f74a231ca4edd2dc6
rm -f /OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.n2n_installed
rm -f /OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/n2n-gitn2n_v2/.configured_*
touch /OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/n2n-gitn2n_v2/.configured_nyynn
make CC="ccache_cc" -C /OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/n2n-gitn2n_v2/n2n_v2
make[3]: Entering directory '/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/n2n-gitn2n_v2/n2n_v2'
make[3]: *** No targets specified and no makefile found.  Stop.
make[3]: Leaving directory '/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/n2n-gitn2n_v2/n2n_v2'
Makefile:76: recipe for target '/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/n2n-gitn2n_v2/.built' failed
make[2]: *** [/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/n2n-gitn2n_v2/.built] Error 2
make[2]: Leaving directory '/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/package/n2n'
package/Makefile:191: recipe for target 'package/n2n/compile' failed
make[1]: *** [package/n2n/compile] Error 2
make[1]: Leaving directory '/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64'
/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/include/toplevel.mk:174: recipe for target 'package/n2n/compile' failed
make: *** [package/n2n/compile] Error 2

Can't compile, how to solve, can you help me?thanks.

**Comment by lucktu** [comment]
try it, Is this what you need?
https://pan.baidu.com/s/1eRNybCm Password: hq4i

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
