### ISSUE TITLE
issue on communication among the edges

### ISSUE THREAD

**Issue by isabelle1208** [meyerd/n2n#33]
I have run the supernode on host 1, edge 1 on host 2, edge 2 on host 3.
However, I saw the problem. The communication between edge 1 and edge 2 is not a kind of peers-to-peers networking.  When I check the VPN connectivity on edge 1 by typing ping 3.3.3.3 ( virtual ip on edge 2),  the packet from edge 1 arrives the supernode, and then the supernode forwards the packet to edge 2.
I hope that you can give me answer.
Thanks.

**Comment by lucktu** [comment]
First, Is it using n2n_v2 (v2.1) here?
Second, p2p isn't 100%. 
Suggest, ping it again after 3 minutes, you will get p2p Very likely.

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
