### ISSUE TITLE
A suggestion about p2p (direct)

### ISSUE THREAD

**Issue by lucktu** [meyerd/n2n#36]
The status(forward/direct) isn't changed in continuous communication by using edge v2. at the same time, zerotier isn't so, it's positive to change, easily to p2p, and it's unstable in forward. 

So I suggest: Add a parameter (D,direct), using the parameter, edge_v2 is runing like zerotier until it's p2p (or in 10 minutes). when it's p2p, give a continuous pinging to hold the p2p.

Do not know whether it is feasible? Thank you very much!

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
