### ISSUE TITLE
Unable to work in MAC OS X 10.13.3

### ISSUE THREAD

**Issue by galaxy001** [meyerd/n2n#37]
````bash
$ sudo ./edge -d edge1 -a 10.0.0.11 -c p2pnet -k p2ppwd -l x.x.x.x:p -m ae:a0:af:a7:47:5c -fv
28/Mar/2018 17:45:03 [/Users/galaxy/git/etc/n2n/n2n_v2/edge.c:2610] Starting n2n edge 2.1.0 Mar 28 2018 17:28:03
28/Mar/2018 17:45:03 [/Users/galaxy/git/etc/n2n/n2n_v2/edge.c:2615] supernode 0 => x.x.x.x:p
28/Mar/2018 17:45:03 [/Users/galaxy/git/etc/n2n/n2n_v2/edge.c:2615] supernode 1 =>
28/Mar/2018 17:45:03 [/Users/galaxy/git/etc/n2n/n2n_v2/edge.c:2662] ip_mode='static'
28/Mar/2018 17:45:03 [/Users/galaxy/git/etc/n2n/n2n_v2/tuntap_osx.c:  48] ERROR: Unable to open tap device

$ ./supernode -l 12345 -fv
28/Mar/2018 17:50:00 [/Users/galaxy/git/etc/n2n/n2n_v2/sn.c: 774] supernode is listening on UDP 12345 (main)
28/Mar/2018 17:50:00 [/Users/galaxy/git/etc/n2n/n2n_v2/n2n.c:  87] ERROR: Bind error [Address already in use]
28/Mar/2018 17:50:00 [/Users/galaxy/git/etc/n2n/n2n_v2/sn.c: 780] ERROR: Failed to open management socket. Address already in use
````

However, the git version works under Linux.

**Comment by songsen** [comment]
Maybe you need install TUN driver .

**Comment by galaxy001** [comment]
I find Apple has offer `net/if_utun.h`.

As mentioned in <https://github.com/songgao/water/issues/3>, OpenVPN has support MAC OSX [natively](https://github.com/OpenVPN/openvpn/blob/master/src/openvpn/tun.c).

The latest [tuntap for osx](http://tuntaposx.sourceforge.net/download.xhtml) is released in 2015, which sounds not good.

Hoping there will be a update.

**Comment by crcrcr999** [comment]
brew cask install tuntap
查看是否有如下两个内核扩展
ls /Library/Extensions/tap.kext
ls /Library/Extensions/tun.kext
校验内核扩展的参数
find /Library/Extensions/{tap,tun}.kext/ -type f | xargs shasum
加载内核扩展
sudo /sbin/kextload /Library/Extensions/tap.kext
sudo /sbin/kextload /Library/Extensions/tun.kext
在尝试运行下连接试试应该就可以了,如果还是不行的话别忘记里尝试加上sudo用root权限执行下试试呢

**Comment by galaxy001** [comment]
I hope you can use the native solution as OpenVPN did, and I'd like to test it on my Mac.

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
