### ISSUE TITLE
An app for android without root is coming !

### ISSUE THREAD

**Issue by lucktu** [meyerd/n2n#39]
https://github.com/switch-iot/n2n_vLTS

**Comment by switch-st** [comment]
:thumbsup::thumbsup::thumbsup:

**Comment by meyerd** [comment]
Hi people. A nice thing, n2n can be used on android, but could you please also give instructions and documentation in english to make it a bit more accessible. That would be great.

**Comment by switch-st** [comment]
@meyerd Thank you for your attention.I will improve the English document within a few days.:blush:

**Comment by switch-st** [comment]
English instructions have been updated.
https://github.com/switch-iot/n2n_vLTS/blob/dev_android_v0.6.0/README.md

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
