### ISSUE TITLE
Unable to compile on windows with vs 2013

### ISSUE THREAD

**Issue by iminsightman** [meyerd/n2n#43]
Hello.
i'm trying to compile n2n_v2 for my windows 10 using vs 2013.
i'm stuck on these errors:
`1>win-scm.obj : error LNK2001: unresolved external symbol _snprintf`
`1>edge.exe : fatal error LNK1120: 1 unresolved externals`
i just need the supernode.exe maybe someone can provide me a link of an already compiled supernode.exe?

**Comment by chaoyuechen** [comment]
[supernode.zip](https://github.com/meyerd/n2n/files/2607432/supernode.zip)

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
