### ISSUE TITLE
n2n speed is too slow!

### ISSUE THREAD

**Issue by hewenhao2008** [meyerd/n2n#47]
I have tested the speed between 2 n2n_v2 edge by iperf3 , the result is only about 3-4Mbps. The first edge is on window use n2ngui.exe, another edge is on debian.   
   I also installed openvpn client on the same windows and debian ,then get  speed result reach to about 30Mbps!  By the way the supernode of n2n and openvpn server are installed on the same VPS.
   So , I think there is something wrong on this version of n2n_v2.

**Comment by lucktu** [comment]
Yes, in Windows, all of n2n is slow.

**Comment by Pummelchen** [comment]
https://github.com/ntop/n2n/issues/87

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
