### ISSUE TITLE
How to print DEBUG infos?

### ISSUE THREAD

**Issue by isabelle1208** [meyerd/n2n#49]
Hi !
I modified CMakeLists.txt and add some codes like this:
if(CMAKE_BUILD_TYPE STREQUAL Debug)
ADD_DEFINITIONS(-DDEBUG)
endif()
But there are no DEBUG infos to print.

Please tell me how to print DEBUG infos. 
Can you reply me soon? Thanks.

**Comment by meyerd** [comment]
You have to set the build type for CMake to Debug by uncommenting 

`set(CMAKE_BUILD_TYPE Debug)`

or using the command line argument 

`cmake -DCMAKE_BUILD_TYPE=Debug`

**Comment by isabelle1208** [comment]
Yes，I do it like this. However there is still no infomations to print on the console.

发自我的 iPhone

**Comment by meyerd** [comment]
have you tried using multiple `-v` on start of the edge process or the `+verb` command on the management socket?

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
