### ISSUE TITLE
Supernode not responding

### ISSUE THREAD

**Issue by sunpanke** [meyerd/n2n#52]
edge -d n2n0 -c mynetwork -k encryptme -a 10.0.0.1 -l x.x.x.x:1000 -f
Starting n2n edge 2.1.0 May 22 2019 09:50:30
supernode 0 => x.x.x.x:1000
ip_mode='static'
 Interface n2n0 has MAC C6:00:8E:72:12:B9
 edge started
Chose new tx_transop_idx=1
 WARNING: Supernode not responding - moving to 0 of 1

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
