### ISSUE TITLE
file cannot create directory: /usr/share/man8.

### ISSUE THREAD

**Issue by Tonigt** [meyerd/n2n#54]
[  6%] Built target scm
[ 17%] Built target doc
[ 65%] Built target n2n
[ 72%] Built target n2n_test
[ 79%] Built target benchmark
[ 86%] Built target supernode
[ 93%] Built target edge
[100%] Built target benchmark_hashtable
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/sbin/edge
-- Installing: /usr/local/sbin/supernode
CMake Error at cmake_install.cmake:64 (file):
  file cannot create directory: /usr/share/man8.  Maybe need administrative
  privileges.

make: *** [install] Error 1

-----------------------
mac version 10.13.6 (17G6030)

**Comment by meyerd** [comment]
hi, the actively maintained version can be found at https://github.com/ntop/n2n
