### ISSUE TITLE
build error on mac 10.14.6

### ISSUE THREAD

**Issue by jack338c** [meyerd/n2n#55]
Jackss-iMac:n2n_v2 jacks$ cd build
Jackss-iMac:build jacks$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jacks/n2n/n2n_v2/build
Jackss-iMac:build jacks$ make
[ 68%] Built target scm
[ 68%] Built target doc
[ 68%] Built target n2n
[ 68%] Linking C executable n2n_test
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [n2n_test] Error 1
make[1]: *** [CMakeFiles/n2n_test.dir/all] Error 2
make: *** [all] Error 2

according to https://blog.csdn.net/nokiaxjw/article/details/88872172
it works on mac 10.13.6 ,but not on macos 10.14.6 
Could you tell me how to fix this

thanks

**Comment by bluce-clj** [comment]
edit CMakeList.txt

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -I${OPENSSL_INCLUDE_DIR}")
change to:
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -L${OPENSSL_ROOT_DIR}/lib -I${OPENSSL_INCLUDE_DIR}")

fix it!

**Comment by jack338c** [comment]
Got it
Thank you !
