### ISSUE TITLE
Problem ver 2.1

### ISSUE THREAD

**Issue by RobJrCG** [meyerd/n2n#58]
Client Version

![Client](https://user-images.githubusercontent.com/25929252/131901042-1e713e11-c4f5-4b02-904a-dabaf1477a21.PNG)

Server Version

![Server](https://user-images.githubusercontent.com/25929252/131901100-9b90650f-0084-4f81-bb67-237ea42dab4f.PNG)

Error:

![Error](https://user-images.githubusercontent.com/25929252/131901489-62280751-865f-4fff-b3a4-4f1911a43323.PNG)

What could be causing this problem?

**Comment by RobJrCG** [comment]
Solved with version v2 from:

https://github.com/certik/n2n

**Comment by meyerd** [comment]
the actively maintained n2n version can be found here: https://github.com/ntop/n2n
