### ISSUE TITLE
is it possible to use multiple udp channel to increase the bandwidth between too edges?

### ISSUE THREAD

**Issue by yunfan** [meyerd/n2n#9]
if it could be. i suggest to use a special rules to tell edge

like    `edge_ip link add rule -dest ip:port -action channel:+10`

**Comment by meyerd** [comment]
I don't get, what this should help with. Normally, the whole bandwidth of the physical network should be able to be taken up by a single udp connection.

**Comment by yunfan** [comment]
but atually i found multiple udp channel could send much more data in less time

**Comment by meyerd** [comment]
You are more than welcome to implement such a capability in n2n. Certainly, it won't be very straight-forward and would require some substantial changes in the routing logic ...
